package com.htc.android.teeter;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int a = 0x7f060000;
        public static final int b = 0x7f060001;
        public static final int c = 0x7f060002;
        public static final int d = 0x7f060003;
        public static final int e = 0x7f060004;
        public static final int f = 0x7f060005;
        public static final int g = 0x7f060006;
        public static final int h = 0x7f060007;
        public static final int i = 0x7f060008;
        public static final int j = 0x7f060009;
        public static final int k = 0x7f06000a;
    }

    public static final class dimen {
        public static final int loading_width = 0x7f070000;
        public static final int loading_height = 0x7f070001;
        public static final int loading_position_x = 0x7f070002;
        public static final int loading_position_y = 0x7f070003;
    }

    public static final class drawable {
        public static final int ball = 0x7f020000;
        public static final int end = 0x7f020001;
        public static final int end_anim = 0x7f020002;
        public static final int facet = 0x7f020003;
        public static final int hole = 0x7f020004;
        public static final int hole_anim_001 = 0x7f020005;
        public static final int hole_anim_002 = 0x7f020006;
        public static final int hole_anim_003 = 0x7f020007;
        public static final int hole_anim_004 = 0x7f020008;
        public static final int hole_anim_005 = 0x7f020009;
        public static final int hole_anim_006 = 0x7f02000a;
        public static final int hole_anim_007 = 0x7f02000b;
        public static final int hole_anim_008 = 0x7f02000c;
        public static final int hole_anim_009 = 0x7f02000d;
        public static final int hole_anim_010 = 0x7f02000e;
        public static final int hole_anim_011 = 0x7f02000f;
        public static final int hole_anim_012 = 0x7f020010;
        public static final int hole_anim_013 = 0x7f020011;
        public static final int hole_anim_014 = 0x7f020012;
        public static final int hole_anim_015 = 0x7f020013;
        public static final int hole_anim_016 = 0x7f020014;
        public static final int hole_anim_017 = 0x7f020015;
        public static final int hole_anim_018 = 0x7f020016;
        public static final int hole_anim_019 = 0x7f020017;
        public static final int hole_anim_020 = 0x7f020018;
        public static final int icon = 0x7f020019;
        public static final int maze = 0x7f02001a;
        public static final int prot_htc_logo = 0x7f02001b;
        public static final int shadow = 0x7f02001c;
        public static final int splash__hvga_bg = 0x7f02001d;
        public static final int splash_hvga_0001 = 0x7f02001e;
        public static final int splash_hvga_0002 = 0x7f02001f;
        public static final int splash_hvga_0003 = 0x7f020020;
        public static final int splash_hvga_0004 = 0x7f020021;
        public static final int splash_hvga_0005 = 0x7f020022;
        public static final int splash_hvga_0006 = 0x7f020023;
        public static final int splash_hvga_0007 = 0x7f020024;
        public static final int splash_hvga_0008 = 0x7f020025;
        public static final int splash_hvga_0009 = 0x7f020026;
        public static final int splash_hvga_0010 = 0x7f020027;
        public static final int splash_hvga_0011 = 0x7f020028;
        public static final int splash_hvga_0012 = 0x7f020029;
        public static final int splash_hvga_0013 = 0x7f02002a;
        public static final int splash_hvga_0014 = 0x7f02002b;
        public static final int splash_hvga_0015 = 0x7f02002c;
        public static final int splash_hvga_0016 = 0x7f02002d;
        public static final int splash_hvga_0017 = 0x7f02002e;
        public static final int splash_hvga_0018 = 0x7f02002f;
        public static final int splash_hvga_0019 = 0x7f020030;
        public static final int splash_hvga_0020 = 0x7f020031;
        public static final int splash_hvga_0021 = 0x7f020032;
        public static final int splash_hvga_0022 = 0x7f020033;
        public static final int splash_hvga_0023 = 0x7f020034;
        public static final int splash_hvga_0024 = 0x7f020035;
        public static final int splash_hvga_0025 = 0x7f020036;
        public static final int splash_hvga_0026 = 0x7f020037;
        public static final int splash_hvga_0027 = 0x7f020038;
        public static final int splash_hvga_0028 = 0x7f020039;
        public static final int splash_hvga_0029 = 0x7f02003a;
        public static final int splash_hvga_0030 = 0x7f02003b;
        public static final int splash_hvga_0031 = 0x7f02003c;
        public static final int splash_hvga_0032 = 0x7f02003d;
        public static final int splash_hvga_0033 = 0x7f02003e;
        public static final int splash_hvga_0034 = 0x7f02003f;
        public static final int splash_hvga_0035 = 0x7f020040;
        public static final int splash_hvga_0036 = 0x7f020041;
        public static final int splash_hvga_0037 = 0x7f020042;
        public static final int splash_hvga_0038 = 0x7f020043;
        public static final int splash_hvga_0039 = 0x7f020044;
        public static final int splash_hvga_0040 = 0x7f020045;
        public static final int splash_hvga_0041 = 0x7f020046;
        public static final int splash_hvga_0042 = 0x7f020047;
        public static final int splash_hvga_0043 = 0x7f020048;
        public static final int splash_hvga_0044 = 0x7f020049;
        public static final int splash_hvga_0045 = 0x7f02004a;
        public static final int splash_hvga_0046 = 0x7f02004b;
        public static final int splash_hvga_0047 = 0x7f02004c;
        public static final int splash_hvga_0048 = 0x7f02004d;
        public static final int splash_hvga_0049 = 0x7f02004e;
        public static final int splash_hvga_0050 = 0x7f02004f;
        public static final int splash_hvga_0051 = 0x7f020050;
        public static final int splash_hvga_0052 = 0x7f020051;
        public static final int splash_hvga_0053 = 0x7f020052;
        public static final int splash_hvga_0054 = 0x7f020053;
        public static final int splash_hvga_0055 = 0x7f020054;
        public static final int splash_hvga_0056 = 0x7f020055;
        public static final int splash_hvga_0057 = 0x7f020056;
        public static final int splash_hvga_0058 = 0x7f020057;
        public static final int splash_hvga_0059 = 0x7f020058;
        public static final int splash_hvga_0060 = 0x7f020059;
        public static final int wall = 0x7f02005a;
        public static final int transparent_background = 0x7f02005b;
    }

    public static final class id {
        public static final int score_layout = 0x7f0a0000;
        public static final int level_caption = 0x7f0a0001;
        public static final int level_time_score = 0x7f0a0002;
        public static final int level_attempt_score = 0x7f0a0003;
        public static final int total_time_score = 0x7f0a0004;
        public static final int total_attempt_score = 0x7f0a0005;
        public static final int rank_scores1 = 0x7f0a0006;
        public static final int rank_scores2 = 0x7f0a0007;
        public static final int rank_scores3 = 0x7f0a0008;
        public static final int rank_scores4 = 0x7f0a0009;
        public static final int rank_scores5 = 0x7f0a000a;
        public static final int btn_restart = 0x7f0a000b;
        public static final int btn_quit = 0x7f0a000c;
        public static final int prot_logo = 0x7f0a000d;
        public static final int prot_msg = 0x7f0a000e;
    }

    public static final class layout {
        public static final int layout01 = 0x7f030000;
        public static final int layout02 = 0x7f030001;
        public static final int prot_custview = 0x7f030002;
    }

    public static final class raw {
        public static final int game_complete = 0x7f050000;
        public static final int hole = 0x7f050001;
        public static final int level_complete = 0x7f050002;
    }

    public static final class string {
        public static final int str_app_name = 0x7f080000;
        public static final int htc_private_app = 0x7f080001;
        public static final int ap_version_id = 0x7f080002;
        public static final int htc_company_short_name = 0x7f080003;
        public static final int str_msg_continue = 0x7f080004;
        public static final int str_msg_quit = 0x7f080005;
        public static final int str_btn_restart = 0x7f080006;
        public static final int str_btn_yes = 0x7f080007;
        public static final int str_btn_no = 0x7f080008;
        public static final int str_btn_resume = 0x7f080009;
        public static final int str_btn_quit = 0x7f08000a;
        public static final int str_level_caption = 0x7f08000b;
        public static final int str_level_time = 0x7f08000c;
        public static final int str_level_attempt = 0x7f08000d;
        public static final int str_total_time = 0x7f08000e;
        public static final int str_total_attempt = 0x7f08000f;
        public static final int str_rank_caption = 0x7f080010;
        public static final int str_no_sensor = 0x7f080011;
        public static final int ap_prot_err = 0x7f080012;
    }

    public static final class style {
        public static final int Theme = 0x7f090000;
        public static final int Theme_FullScreen = 0x7f090001;
    }

    public static final class xml {
        public static final int config_click_wwe = 0x7f040000;
        public static final int config_dragon_wwe = 0x7f040001;
        public static final int config_dream_wwe = 0x7f040002;
        public static final int config_sapphire_wwe = 0x7f040003;
        public static final int level001 = 0x7f040004;
        public static final int level002 = 0x7f040005;
        public static final int level003 = 0x7f040006;
        public static final int level004 = 0x7f040007;
        public static final int level005 = 0x7f040008;
        public static final int level006 = 0x7f040009;
        public static final int level007 = 0x7f04000a;
        public static final int level008 = 0x7f04000b;
        public static final int level009 = 0x7f04000c;
        public static final int level010 = 0x7f04000d;
        public static final int level011 = 0x7f04000e;
        public static final int level012 = 0x7f04000f;
        public static final int level013 = 0x7f040010;
        public static final int level014 = 0x7f040011;
        public static final int level015 = 0x7f040012;
        public static final int level016 = 0x7f040013;
        public static final int level017 = 0x7f040014;
        public static final int level018 = 0x7f040015;
        public static final int level019 = 0x7f040016;
        public static final int level020 = 0x7f040017;
        public static final int level021 = 0x7f040018;
        public static final int level022 = 0x7f040019;
        public static final int level023 = 0x7f04001a;
        public static final int level024 = 0x7f04001b;
        public static final int level025 = 0x7f04001c;
        public static final int level026 = 0x7f04001d;
        public static final int level027 = 0x7f04001e;
        public static final int level028 = 0x7f04001f;
        public static final int level029 = 0x7f040020;
        public static final int level030 = 0x7f040021;
        public static final int level031 = 0x7f040022;
        public static final int level032 = 0x7f040023;
    }
}